# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"

  - package-ecosystem: npm
    directory: "/docs"
    schedule:
      interval: weekly
    # DevRel should review docs updates
    # assignees:
    #   - "julienrbrt"

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "01:05"
    labels:
      - "A:automerge"
      - dependencies
  - package-ecosystem: gomod
    directory: "/simapp"
    schedule:
      interval: daily
      time: "01:10"
    labels:
      - "A:automerge"
      - dependencies
  - package-ecosystem: gomod
    directory: "/tests"
    schedule:
      interval: weekly
      day: monday
      time: "01:15"
    labels:
      - "A:automerge"
      - dependencies
  - package-ecosystem: gomod
    directory: "/api"
    schedule:
      interval: weekly
      day: tuesday
      time: "01:20"
    labels:
      - "A:automerge"
      - dependencies

  - package-ecosystem: gomod
    directory: "/x/foundation"
    schedule:
      interval: weekly
      day: monday
      time: "01:25"
    labels:
      - "A:automerge"
      - dependencies
  - package-ecosystem: gomod
    directory: "/x/collection"
    schedule:
      interval: weekly
      day: tuesday
      time: "01:30"
    labels:
      - "A:automerge"
      - dependencies
  - package-ecosystem: gomod
    directory: "/x/stakingplus"
    schedule:
      interval: weekly
      day: wednesday
      time: "01:35"
    labels:
      - "A:automerge"
      - dependencies
  - package-ecosystem: gomod
    directory: "/x/bankplus"
    schedule:
      interval: weekly
      day: thursday
      time: "01:40"
    labels:
      - "A:automerge"
      - dependencies

  # # Dependencies should be up to date on release branch
  # - package-ecosystem: gomod
  #   directory: "/"
  #   target-branch: "release/v0.47.x"
  #   schedule:
  #     interval: daily
  #     time: "03:00"
  #   labels:
  #     - "A:automerge"
  #     - dependencies
  #     - "testing-required"
  #   allow:
  #     - dependency-name: "github.com/cosmos/cosmos-sdk/*"
  #       dependency-type: "all"
  #     - dependency-name: "github.com/cosmos/*"
  #       dependency-type: "all"
  #     - dependency-name: "cosmossdk.io/*"
  #       dependency-type: "all"

  # # Dependencies should be up to date on release branch
  # - package-ecosystem: gomod
  #   directory: "/"
  #   target-branch: "release/v0.50.x"
  #   schedule:
  #     interval: daily
  #     time: "03:00"
  #   labels:
  #     - "A:automerge"
  #     - dependencies
  #     - "testing-required"
  #   allow:
  #     - dependency-name: "github.com/cosmos/cosmos-sdk/*"
  #       dependency-type: "all"
  #     - dependency-name: "github.com/cosmos/*"
  #       dependency-type: "all"
  #     - dependency-name: "cosmossdk.io/*"
  #       dependency-type: "all"
