"A: build":
  - Makefile
  - Dockerfile
  - docker-compose.yml
  - scripts/*
"A: CI":
  - .github/**/*.yml
  - buf.yaml
  - .mergify.yml
  - .golangci.yml
# "C:CLI":
#   - client/**/*
#   - x/*/client/**/*
# "Type: ADR":
#   - docs/architecture/**/*
"C:x/bankplus":
  - x/bankplus/**/*