name: generate swagger
description: generate swagger files based on protobuf
runs:
  using: "composite"
  steps:
    - run: make proto-swagger-gen
      shell: sh
    - run: make update-swagger-docs
      shell: sh
