# name: Add Sprint issues to Finschia SDK Project

# on:
#   issues:
#     types:
#       - opened
#       - labeled

# jobs:
#   add-to-project:
#     name: Add issue to project
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/add-to-project@v0.5.0
#         with:
#           project-url: https://github.com/orgs/Finschia/projects/26
#           github-token: ${{ secrets.PERSONAL_TOKEN }}
#           labeled: T:Sprint,needs-triage
