name: Lint
# Lint runs golangci-lint over the entire cosmos-sdk repository
# This workflow is run on every pull request and push to main
# The `golangci` will pass without running if no *.{go, mod, sum} files have been changed.
env:
  GOPRIVATE: "github.com/line/*"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/setup-go@v3.3.0
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.1
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: golangci/golangci-lint-action@master
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.47.2
          args: --timeout 10m
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: env.GIT_DIFF
