name: publish
on:
  pull_requests:
  push:
    tags:
      - v*
env:
  registry: docker.io
  repository: line/lbm-simapp
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: login to the registry
        uses: docker/login-action@v1
        with:
          registry: ${{env.registry}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: extract metadata for docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{env.registry}}/${{env.repository}}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=pr
      - name: docker build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
