name: Sims
# Sims workflow runs multiple types of simulations (nondeterminism, import-export, after-import, multi-seed-short)
# This workflow will run on all Pull Requests, if a .go, .mod or .sum file have been changed

env:
  GOPRIVATE: "github.com/Finschia"

on:
  pull_request:
    branches-ignore:
      - "release/*"
  push:
    branches:
      - main
      - rc*/*

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-sims')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4.0.0
        with:
          go-version: 1.19
      - name: Display go version
        run: go version
      - name: Add SSH Go Module Private Key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.PRIVATE_REPO_SSH_KEY }}"
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
      - name: Setup access for private go modules
        run: |
          git config --global url."ssh://git@github.com/".insteadOf https://github.com/
      # - uses: getsentry/action-github-app-token@v2.0.0
      #   id: get-github-token
      #   with:
      #     app_id: ${{ secrets.CI_GITHUB_APP_ID }}
      #     private_key: ${{ secrets.CI_GITHUB_APP_PRIVATE_KEY }}
      # - name: Set git config
      #   env:
      #     GITHUB_TOKEN: ${{ steps.get-github-token.outputs.token }}
      #   run: |
      #     git config --global url."https://x-access-token:$GITHUB_TOKEN@github.com/".insteadOf https://github.com/
      - run: make build

  install-runsim:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/setup-go@v4.0.0
        with:
          go-version: 1.19
      - name: Display go version
        run: go version
      - name: Install runsim
        run: export GO111MODULE="on" && go install github.com/cosmos/tools/cmd/runsim@v1.0.0
      - uses: actions/cache@v3.3.1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary

  test-sim-nondeterminism-short:
    runs-on: ubuntu-latest
    needs: [build, install-runsim]
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.PRIVATE_REPO_SSH_KEY }}
      - uses: actions/setup-go@v4.0.0
        with:
          go-version: 1.19
      - name: Display go version
        run: go version
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            !**/**_test.go
            go.mod
            go.sum
      - uses: actions/cache@v3.3.1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
        if: env.GIT_DIFF
      - name: test-sim-nondeterminism-short
        run: |
          make test-sim-nondeterminism-short
        if: env.GIT_DIFF

  test-sim-import-export-short:
    runs-on: ubuntu-latest
    needs: [build, install-runsim]
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.PRIVATE_REPO_SSH_KEY }}
      - uses: actions/setup-go@v4.0.0
        with:
          go-version: 1.19
      - name: Display go version
        run: go version
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            !**/**_test.go
            go.mod
            go.sum
          SET_ENV_NAME_INSERTIONS: 1
          SET_ENV_NAME_LINES: 1
      - uses: actions/cache@v3.3.1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
        if: env.GIT_DIFF
      - name: test-sim-import-export-short
        run: |
          make test-sim-import-export-short
        if: env.GIT_DIFF

  test-sim-after-import-short:
    runs-on: ubuntu-latest
    needs: [build, install-runsim]
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.PRIVATE_REPO_SSH_KEY }}
      - uses: actions/setup-go@v4.0.0
        with:
          go-version: 1.19
      - name: Display go version
        run: go version
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            !**/**_test.go
            go.mod
            go.sum
          SET_ENV_NAME_INSERTIONS: 1
          SET_ENV_NAME_LINES: 1
      - uses: actions/cache@v3.3.1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
        if: env.GIT_DIFF
      - name: test-sim-after-import-short
        run: |
          make test-sim-after-import-short
        if: env.GIT_DIFF

  test-sim-multi-seed-short:
    runs-on: ubuntu-latest
    needs: [build, install-runsim]
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.PRIVATE_REPO_SSH_KEY }}
      - uses: actions/setup-go@v4.0.0
        with:
          go-version: 1.19
      - name: Display go version
        run: go version
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            !**/**_test.go
            go.mod
            go.sum
          SET_ENV_NAME_INSERTIONS: 1
          SET_ENV_NAME_LINES: 1
      - uses: actions/cache@v3.3.1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
        if: env.GIT_DIFF
      - name: test-sim-multi-seed-short
        run: |
          make test-sim-multi-seed-short
        if: env.GIT_DIFF
